# Generated by Django 2.1.2 on 2018-10-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20181021_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='update',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
    ]
